[package]
name = "g4_bring_path_into_scope_with_use_keyword"
version = "0.1.0"
authors = ["valentinodg <valentino.digiosaffatte@student.univaq.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
