[package]
name = "k1_how_to_write_tests"
version = "0.1.0"
authors = ["valentino <valentino.digiosaffatte@student.univaq.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
